apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: [CRB_NAME]
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-anyuid-hostpath-clusterrole
subjects:
- kind: Group
  name: system:serviceaccounts:[TARGET_NAMESPACE]
  apiGroup: rbac.authorization.k8s.io
